dotnet restore ./RossmannProductFetcher/ProductFetcherService/ProductFetcherService.sln
dotnet restore ./RossmannProductFetcher/ProductFetcherApi/ProductFetcherApi.sln
dotnet build ./RossmannProductFetcher/ProductFetcherService/ProductFetcherService.sln
dotnet build ./RossmannProductFetcher/ProductFetcherApi/ProductFetcherApi.sln